# ============================================
# SkyOrbs 2.0.0 - Türkçe Gezegen Sistemi
# ============================================

# Gezegen Üretim Ayarları
generation:
  planetSize:
    minRadius: 25          # Minimum gezegen yarıçapı (çok küçük - hızlı)
    maxRadius: 50          # Maximum gezegen yarıçapı (çok küçük - hızlı)
    averageRadius: 35      # Ortalama gezegen boyutu (çok küçük - hızlı)
    
    # Boyut kategorileri (opsiyonel)
    small: 80-120
    medium: 120-180
    large: 180-250

# Gezegen Yerleştirme
placement:
  worldBounds:
    centerX: 0                    # Dünya merkez X
    centerZ: 0                    # Dünya merkez Z
    maxDistance: 5000             # Spawn'dan maksimum uzaklık (artırıldı)
    minDistanceFromSpawn: 1500    # Spawn'dan minimum uzaklık (artırıldı)
  
  clustering:
    enabled: true                 # Gezegenleri kümeleme
    clusterMinDistance: 2000      # Kümede minimum mesafe (çok artırıldı)
    clusterMaxDistance: 4000      # Kümede maksimum mesafe (çok artırıldı)
  
  attractToCenter:
    centerAttraction: 0.3         # Merkeze çekim kuvveti (0.0-1.0)

# Gezegen Şekilleri ve Ağırlıkları
shapes:
  weights:
    # Basic shapes (10)
    SPHERE: 8.0         # Küre
    HEMISPHERE: 15.0    # Yarım Küre
    BLOB: 12.0          # Ameba
    ELLIPSOID: 10.0     # Elips
    ASTEROID: 8.0       # Asteroid
    TORUS: 6.0          # Çörek
    RING: 3.0           # Halka
    CYLINDER: 5.0       # Silindir
    CONE: 7.0           # Koni
    DIAMOND: 6.0        # Elmas

    # Advanced shapes (10)
    CUBE: 4.0           # Küp
    PYRAMID: 3.0        # Piramit
    OCTAHEDRON: 2.0     # Sekizyüzlü
    FRACTAL: 2.0        # Fraktal
    SPIKY: 1.5          # Dikenli
    COMET: 1.0          # Kuyruklu yıldız
    CRESCENT: 1.0       # Hilal
    HYBRID: 0.5         # Karma

    # Diverse shapes (10 more)
    LAYERED: 4.0        # Katmanlı
    ASTEROID_FIELD: 2.0 # Asteroid alanı
    CRATERED: 3.0       # Kraterli
    HONEYCOMB: 2.0      # Bal peteği
    SPIRAL: 1.5         # Spiral
    WAVE: 2.5           # Dalgalı
    CRYSTAL: 3.0        # Kristal
    ORGANIC: 4.0        # Organik
    GEOMETRIC: 2.0      # Geometrik
    NEBULA: 1.0         # Nebula

# Asteroid Sistemi
asteroids:
  enabled: true
  perPlanet:
    minCount: 1               # Gezegen başına minimum asteroid
    maxCount: 5               # Gezegen başına maksimum asteroid
  size:
    minRadius: 20             # Minimum asteroid boyutu
    maxRadius: 50             # Maksimum asteroid boyutu
  placement:
    minDistanceFromPlanet: 300
    maxDistanceFromPlanet: 800

# Uydu Sistemi
satellites:
  enabled: true
  perPlanet:
    minCount: 0               # Gezegen başına minimum uydu
    maxCount: 3               # Gezegen başına maksimum uydu
    probability: 0.6          # Uydu olma olasılığı (60%)
  size:
    minRadius: 30
    maxRadius: 70
  ring_chance: 0.2            # Halka olma olasılığı (20%)

# Planet Modifiers (for 2000+ combinations)
modifiers:
  enabled: true
  hollow:
    enabled: true
    probability: 0.4              # 40% chance for hollow planets
    shellThickness: 5             # Shell thickness in blocks
    tunnelCount: 3                # Number of interior tunnels
    structureTemplates:           # Civilization feeling structures
      - "ruins_small"
      - "lab_fragment"
      - "alien_base_remnant"
      - "ancient_temple"

  oreRich:
    enabled: true
    probability: 0.3              # 30% chance for ore-rich planets
    multiplier: 2.0               # 2x ore density

  magmaCore:
    enabled: true
    probability: 0.2              # 20% chance for magma core
    coreRadius: 0.2               # Core is 20% of planet radius

  icyCore:
    enabled: true
    probability: 0.15             # 15% chance for icy core

  antiGravity:
    enabled: true
    probability: 0.1              # 10% chance for anti-gravity zones

# Atmospheres (8 types)
atmospheres:
  enabled: true
  clear:
    probability: 0.4
    effects: []
    particles: []
    fog: false
    glow: false

  luminous:
    probability: 0.2
    effects:
      - effect: NIGHT_VISION
        amplifier: 0
        duration: 100
    particles: END_ROD
    fog: false
    glow: true

  toxic:
    probability: 0.15
    effects:
      - effect: POISON
        amplifier: 1
        duration: 80
      - effect: SLOWNESS
        amplifier: 0
        duration: 100
    particles: DRIP_LAVA
    fog: true
    glow: false

  stormy:
    probability: 0.1
    effects:
      - effect: SLOWNESS
        amplifier: 1
        duration: 60
    particles: CLOUD
    fog: true
    glow: false

  foggy:
    probability: 0.08
    effects:
      - effect: BLINDNESS
        amplifier: 0
        duration: 40
    particles: SUSPENDED_DEPTH
    fog: true
    glow: false

  corrosive:
    probability: 0.05
    effects:
      - effect: WITHER
        amplifier: 0
        duration: 60
      - effect: POISON
        amplifier: 2
        duration: 100
    particles: PORTAL
    fog: true
    glow: false

  aurora:
    probability: 0.03
    effects:
      - effect: REGENERATION
        amplifier: 0
        duration: 120
    particles: END_ROD
    fog: false
    glow: true

# Flora Themes (10 types)
floraThemes:
  enabled: true
  trees:
    probability: 0.4
    density: 0.25
  fungi:
    probability: 0.2
    density: 0.3
  crystals:
    probability: 0.15
    density: 0.2
  vines:
    probability: 0.1
    density: 0.35
  moss:
    probability: 0.08
    density: 0.4
  luminous_plants:
    probability: 0.05
    density: 0.15
  coral:
    probability: 0.03
    density: 0.1
  flowers:
    probability: 0.02
    density: 0.5
  cacti:
    probability: 0.01
    density: 0.05
  exotic:
    probability: 0.005
    density: 0.08

# Structure Themes (12 types)
structureThemes:
  enabled: true
  ruins:
    probability: 0.25
    templates: ["ruins_small", "ruins_large", "temple_ruins"]
  temple:
    probability: 0.15
    templates: ["alien_temple", "crystal_temple", "void_temple"]
  alien_base:
    probability: 0.1
    templates: ["alien_lab", "alien_habitat", "alien_defense"]
  lab:
    probability: 0.08
    templates: ["research_lab", "bio_lab", "tech_lab"]
  crashed_ship:
    probability: 0.05
    templates: ["small_ship", "medium_ship", "large_ship"]
  fortress:
    probability: 0.03
    templates: ["volcanic_fortress", "ice_fortress", "crystal_fortress"]
  spire:
    probability: 0.02
    templates: ["crystal_spire", "obsidian_spire", "ice_spire"]
  dungeon:
    probability: 0.01
    templates: ["deep_dungeon", "ancient_dungeon", "cursed_dungeon"]
  village:
    probability: 0.005
    templates: ["alien_village", "crystal_village", "fungal_village"]
  portal:
    probability: 0.003
    templates: ["nether_portal", "end_portal", "void_portal"]
  monolith:
    probability: 0.002
    templates: ["ancient_monolith", "crystal_monolith", "energy_monolith"]
  citadel:
    probability: 0.001
    templates: ["floating_citadel", "underground_citadel", "sky_citadel"]

# Satellites/Rings/Asteroids (8 types)
satelliteSystems:
  enabled: true
  none:
    probability: 0.3
  moon:
    probability: 0.25
    count: [1, 1]
    materials: [STONE, ANDESITE, DIORITE]
  debris:
    probability: 0.15
    count: [3, 8]
    materials: [COBBLESTONE, GRAVEL, DIRT]
  asteroids:
    probability: 0.12
    count: [2, 5]
    materials: [STONE, COBBLESTONE, ANDESITE]
  ringed:
    probability: 0.08
    count: [8, 15]
    materials: [STONE, COBBLESTONE, GRAVEL]
  twin_moons:
    probability: 0.05
    count: [2, 2]
    materials: [STONE, ANDESITE, GRANITE]
  mini_moon:
    probability: 0.03
    count: [1, 1]
    materials: [GLOWSTONE, SEA_LANTERN, SHROOMLIGHT]
  planetary_system:
    probability: 0.02
    count: [3, 7]
    materials: [STONE, GLOWSTONE, OBSIDIAN, DIAMOND_BLOCK]

# Performans Optimizasyonu
performance:
  asyncGeneration: true             # Asenkron üretim

  threadPool:
    coreSize: 8                     # Thread havuzu boyutu (2x artırıldı)
    maxSize: 16                     # Maksimum thread sayısı (2x artırıldı)

  batching:
    blocksPerBatch: 1000            # Batch başına blok sayısı (4x artırıldı - çok hızlı)
    batchesPerTick: 4               # Tick başına batch sayısı (4x artırıldı - çok hızlı)

  generation:
    shellThickness: 0                # Artık kullanılmıyor - tam dolu üretim
    chunkPreload: true              # Chunk'ları önceden yükle
  
  worldManagement:
    autoSave:
      enabled: true
      interval: 600                 # Saniye (10 dakika)
    
    chunkUnload:
      enabled: true                 # Chunk unload optimizasyonu
      delay: 200                    # Tick (10 saniye)

# Progress Display
progress_display:
  type: bossbar                     # bossbar, actionbar, or chat
  update_interval: 500              # ms between updates

# Teleportation
teleport:
  safe_teleport: true               # Enable safe teleportation checks
  avoid_dangerous_blocks: true      # Avoid lava, fire, etc.

# Hollow Planets
hollow:
  enabled: true                     # Enable hollow planet generation
  probability: 0.4                  # Chance of generating hollow planets (0.0-1.0)
  shell_thickness: 5                # Thickness of hollow planet shell
  interior_structures: true         # Generate civilization structures inside
  tunnels: true                     # Generate connecting tunnels

# Debug Modu
debug:
  enabled: false                    # Ana debug modu

  oreGeneration:
    enabled: false                  # Ore debug
    showCoordinates: true           # Koordinatları göster
    showVeinSize: true              # Vein boyutunu göster

  treeGeneration:
    enabled: false                  # Ağaç debug
    showTreeType: true

  structureGeneration:
    enabled: false                  # Yapı debug
    showStructureType: true

  performanceMonitor:
    enabled: false                  # Performans monitörü
    logInterval: 100                # Log aralığı (tick)

# Limitler
limits:
  planetsPerPlayer: 5               # Oyuncu başına gezegen limiti (artırıldı)
  maxPlanetsPerWorld: 200           # Dünya başına maksimum gezegen (artırıldı)
  deleteOwnPlanet: true             # Kendi gezegenini silebilir mi (etkinleştirildi)
  generationCooldown: 60            # Gezegen oluşturma cooldown (saniye - azaltıldı)

# Entegrasyonlar
integrations:
  vault:
    enabled: false                  # Vault ekonomi sistemi
    planetCreationCost: 1000.0      # Gezegen oluşturma maliyeti
  
  worldguard:
    enabled: false                  # WorldGuard koruması
    autoProtectPlanets: true        # Gezegenleri otomatik koru
  
  placeholderapi:
    enabled: false                  # PlaceholderAPI
    # Placeholders:
    # %skyorbs_planets% - Toplam gezegen sayısı
    # %skyorbs_player_planets% - Oyuncunun gezegen sayısı
  
  dynmap:
    enabled: false                  # Dynmap entegrasyonu
    showPlanets: true               # Gezegenleri haritada göster
    markerIcon: "world"             # Marker ikonu

# Gezegen İsimleri
planetNames:
  prefixes:
    - "Nova"
    - "Stella"
    - "Astro"
    - "Celest"
    - "Nebu"
    - "Galax"
    - "Cosmo"
    - "Meteor"
    - "Lunar"
    - "Solar"
    - "Void"
    - "Echo"
    - "Zenith"
    - "Quantum"
    - "Ethereal"
  
  suffixes:
    - "prime"
    - "minor"
    - "major"
    - "core"
    - "rim"
    - "sphere"
    - "world"
    - "star"
    - "moon"
    - "rock"
    - "drift"
    - "haven"
    - "nexus"
    - "forge"
    - "sanctum"
  
  postfixes:
    - "Alpha"
    - "Beta"
    - "Gamma"
    - "Delta"
    - "Omega"
    - "Prime"
    - "Secundus"
    - "Tertius"
  
  formats:
    - "{prefix}-{suffix}"
    - "{prefix} {suffix}"
    - "{prefix}-{number}"
    - "{prefix} {postfix}"
    - "{suffix}-{number}"
  
  numberRange:
    min: 1
    max: 999

# Mesajlar
messages:
  prefix: "&8[&bGezegen&8]&r"
  
  # Komut mesajları
  noPermission: "&cBu komutu kullanma yetkiniz yok!"
  playerOnly: "&cBu komut sadece oyuncular tarafından kullanılabilir!"
  configReloaded: "&aKonfigürasyon yeniden yüklendi!"
  
  # Gezegen oluşturma
  planetCreating: "&eGezegen oluşturuluyor..."
  planetCreated: "&a&lGezegen Oluşturuldu!"
  planetCreationFailed: "&cGezegen oluşturulamadı: {reason}"
  noSuitableLocation: "&cUygun konum bulunamadı!"
  
  # Gezegen listesi
  listHeader: "&b&l=== Gezegenler ({count}) ==="
  listEmpty: "&7Henüz gezegen oluşturulmamış."
  
  # Gezegen bilgi
  planetNotFound: "&cGezegen bulunamadı: {name}"
  
  # Teleport
  teleported: "&aGezegene ışınlandınız: &e{name}"
  
  # Silme
  planetDeleting: "&eGezegen siliniyor..."
  planetDeleted: "&aGezegen silindi: &e{name}"
  
  # Limitler
  planetLimitReached: "&cGezegen limitine ulaştınız! (Limit: {limit})"
  cooldownActive: "&cGezegen oluşturmak için {time} saniye beklemelisiniz!"
  
  # Ekonomi
  insufficientFunds: "&cYetersiz para! Gerekli: {cost}"
  economyCharged: "&a{cost} para çekildi."